/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import DAO.AdminDAO;
import DAO.GeneroDAO;
import DAO.MusicaDAO;
import Model.Genero;
import Model.Musica;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class adminDashboardTela extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboardTela
     */
    public adminDashboardTela() {
        initComponents();
        buscarGeneros();
        setLocationRelativeTo(null);
        buscarMusicas();
        
    }
    
    private void buscarMusicas(){
        try{
            ArrayList <Musica> musicas = MusicaDAO.obterMusica();
            musicasComboBox.setModel(new DefaultComboBoxModel<>(musicas.toArray(new Musica[0])));
            
        }
        catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Tente novamente mais tarde");
        }
    }
   
    private void buscarGeneros(){
        try{
            
            ArrayList <Genero> generos = GeneroDAO.obterGenero();
            generosComboBox.setModel(new DefaultComboBoxModel<>(generos.toArray(new Genero[0])));
        }
        catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Tente novamente mais tarde");
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generosComboBox = new javax.swing.JComboBox();
        removerTituloTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addTituloTextField = new javax.swing.JTextField();
        removerOkButton = new javax.swing.JButton();
        addOkButton = new javax.swing.JButton();
        generoTextField = new javax.swing.JTextField();
        artistaTextField = new javax.swing.JTextField();
        removerArtistaTextField = new javax.swing.JTextField();
        musicasComboBox = new javax.swing.JComboBox();
        voltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adicionar musica");

        generosComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        generosComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Generos"));
        generosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generosComboBoxActionPerformed(evt);
            }
        });

        removerTituloTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Titulo"));

        jLabel1.setText("Adicionar musica");

        jLabel2.setText("Remover musica");

        addTituloTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Titulo"));
        addTituloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTituloTextFieldActionPerformed(evt);
            }
        });

        removerOkButton.setText("OK");
        removerOkButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        removerOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerOkButtonActionPerformed(evt);
            }
        });

        addOkButton.setText("OK");
        addOkButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOkButtonActionPerformed(evt);
            }
        });

        generoTextField.setToolTipText("");
        generoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Genero"));
        generoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoTextFieldActionPerformed(evt);
            }
        });

        artistaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Artista"));
        artistaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistaTextFieldActionPerformed(evt);
            }
        });

        removerArtistaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Artista"));
        removerArtistaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerArtistaTextFieldActionPerformed(evt);
            }
        });

        musicasComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        musicasComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Musicas"));
        musicasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicasComboBoxActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar");
        voltarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addTituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(generoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artistaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(removerTituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(removerArtistaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(removerOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(79, 79, 79))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(addOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(musicasComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addTituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(artistaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removerTituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removerArtistaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removerOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(musicasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voltarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removerOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerOkButtonActionPerformed
        // TODO add your handling code here:
        String titulo = removerTituloTextField.getText();
        String genero = "";
        String artista = removerArtistaTextField.getText();
        int codigo = 0;
        Musica musica = new Musica(codigo,titulo,genero,artista);
        try{
            if(AdminDAO.existe(musica)){
                AdminDAO.remover(musica);{
                JOptionPane.showMessageDialog(null, String.format("Musica %s deletada.", musica.getTitulo()));
                removerTituloTextField.setText("");
                removerArtistaTextField.setText("");
                generoTextField.setText("");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Essa musica não existe.");
                removerTituloTextField.setText("");
                removerArtistaTextField.setText("");
                generoTextField.setText("");
                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Por favor tente mais tarde");
            e.printStackTrace();
        }
    }//GEN-LAST:event_removerOkButtonActionPerformed

    private void addOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOkButtonActionPerformed
        // TODO add your handling code here:
       
        String titulo = addTituloTextField.getText();
        String genero = generoTextField.getText();
        int codigo = 0;
        String artista = artistaTextField.getText();
        Musica musica = new Musica(codigo,titulo,genero,artista);
        try{
            if(AdminDAO.existe(musica)){
                JOptionPane.showMessageDialog(null, String.format("Musica %s já existe.",musica.getTitulo()));
                addTituloTextField.setText("");
                artistaTextField.setText("");
                
            }if(titulo.isBlank() || artista.isBlank() || genero.isBlank()){
                JOptionPane.showMessageDialog(null,"Preencha os campos.");
            }else{
                AdminDAO.inserir(musica);{
                JOptionPane.showMessageDialog(null, String.format("Musica %s cadastrada.",musica.getTitulo()));
                addTituloTextField.setText("");
                artistaTextField.setText("");
                buscarMusicas();
            }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Por favor tente mais tarde.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_addOkButtonActionPerformed

    private void generosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generosComboBoxActionPerformed
        // TODO add your handling code here:
             Genero genero = (Genero)generosComboBox.getSelectedItem();
             generoTextField.setText(Integer.toString(genero.getId()));
             
    }//GEN-LAST:event_generosComboBoxActionPerformed

    private void generoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoTextFieldActionPerformed

    private void artistaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artistaTextFieldActionPerformed

    private void removerArtistaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerArtistaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removerArtistaTextFieldActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        adminMainDashboardTela admMainTela = new adminMainDashboardTela();
        this.setVisible(false);
        admMainTela.setVisible(true);
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void musicasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicasComboBoxActionPerformed
        // TODO add your handling code here:
        Musica musica = (Musica)musicasComboBox.getSelectedItem();
        removerArtistaTextField.setText(musica.getArtista());
        removerTituloTextField.setText(musica.getTitulo());
    }//GEN-LAST:event_musicasComboBoxActionPerformed

    private void addTituloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTituloTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTituloTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDashboardTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDashboardTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDashboardTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDashboardTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDashboardTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOkButton;
    private javax.swing.JTextField addTituloTextField;
    private javax.swing.JTextField artistaTextField;
    private javax.swing.JTextField generoTextField;
    private javax.swing.JComboBox generosComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox musicasComboBox;
    private javax.swing.JTextField removerArtistaTextField;
    private javax.swing.JButton removerOkButton;
    private javax.swing.JTextField removerTituloTextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
