/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.User_GeneroDAO;
import DAO.User_MusicaDAO;
import Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class ClienteTela extends javax.swing.JFrame {

    /**
     * Creates new form ClienteTela
     */
    public ClienteTela() {
        initComponents();
        setLocationRelativeTo(null);
        
        
    }
    public String usuario;
    ClienteTela(String usuario) {
        initComponents();
        this.usuario = usuario;
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avaliarButton = new javax.swing.JButton();
        recomendacoesButton = new javax.swing.JButton();
        generosButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");

        avaliarButton.setText("Avaliar músicas");
        avaliarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        avaliarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliarButtonActionPerformed(evt);
            }
        });

        recomendacoesButton.setText("Quero recomendações");
        recomendacoesButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        recomendacoesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recomendacoesButtonActionPerformed(evt);
            }
        });

        generosButton.setText("Meus gêneros preferidos");
        generosButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generosButtonActionPerformed(evt);
            }
        });

        sairButton.setText("SAIR");
        sairButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(generosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avaliarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recomendacoesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(generosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avaliarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recomendacoesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sairButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generosButtonActionPerformed
            // TODO add your handling code here:
        GeneroTela GeneroTela = new GeneroTela(usuario);
        try{GeneroTela.setVisible(true);
            this.setVisible(false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Tente novamente mais tarde.");
            e.printStackTrace();
    }
        
    }//GEN-LAST:event_generosButtonActionPerformed

    private void avaliarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliarButtonActionPerformed
        // TODO add your handling code here:
                MusicaTela musicaTela = new MusicaTela(usuario);
                musicaTela.setVisible(false);
                GeneroTela generoTela = new GeneroTela(usuario);
                generoTela.setVisible(false);
                int usuarioId = 0;
                try{
                    usuarioId = User_MusicaDAO.pegarUserId(usuario);
                }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Não foi possivel pegar o id do usuario");
            e.printStackTrace();
                }
            try{
            if(User_GeneroDAO.jaAvaliou(usuarioId)){
            musicaTela.setVisible(true);
            this.setVisible(false); 
            }else{
                JOptionPane.showMessageDialog(null, "Você deve escolher seus gêneros preferidos antes.");
                generoTela.setVisible(true);
                this.setVisible(false);
            }
            }catch(Exception e){
            JOptionPane.showInputDialog(null,"Por favor tente mais tarde.");
            e.printStackTrace();
        }
            
    }//GEN-LAST:event_avaliarButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
        LoginTela loginTela = new LoginTela();
        loginTela.setVisible(false);
        this.setVisible(false);
        loginTela.setVisible(true);
    }//GEN-LAST:event_sairButtonActionPerformed

    private void recomendacoesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recomendacoesButtonActionPerformed
        // TODO add your handling code here:
        RecomendarTela rTt = new RecomendarTela(usuario);
        
        rTt.setVisible(false);


                GeneroTela generoTela = new GeneroTela(usuario);
                generoTela.setVisible(false);
                int usuarioId = 0;
                try{
                    usuarioId = User_MusicaDAO.pegarUserId(usuario);
                }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Não foi possivel pegar o id do usuario");
            e.printStackTrace();
                }
            try{
            if(User_GeneroDAO.jaAvaliou(usuarioId)){
            this.setVisible(false);
            rTt.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Você deve escolher seus gêneros preferidos antes.");
                generoTela.setVisible(true);
                this.setVisible(false);
            }
            }catch(Exception e){
            JOptionPane.showInputDialog(null,"Por favor tente mais tarde.");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_recomendacoesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avaliarButton;
    private javax.swing.JButton generosButton;
    private javax.swing.JButton recomendacoesButton;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
