/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.GeneroDAO;
import DAO.User_GeneroDAO;
import DAO.User_MusicaDAO;
import Model.Genero;
import Model.User_Genero;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class GeneroTela extends javax.swing.JFrame {

    /**
     * Creates new form GeneroTela
     */
    public GeneroTela() {
        initComponents();
        setLocationRelativeTo(null);
    }
    String usuario;
    GeneroTela(String usuario) {
        this.usuario = usuario;
        initComponents();
        buscarGeneros();
        buscarMeusGeneros();
        
        
        setLocationRelativeTo(null);
    }   
        int usuarioId =0;

        private void buscarMeusGeneros(){
            try{
            usuarioId = User_MusicaDAO.pegarUserId(usuario);
            }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Não foi possivel pegar o id do usuario");
            e.printStackTrace();
            }
        try{
            
            ArrayList <User_Genero> uG = User_GeneroDAO.obterUser_Genero2(usuarioId);
            meusGenerosComboBox.setModel(new DefaultComboBoxModel<>(uG.toArray(new User_Genero[0])));
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Por favor tente mais tarde.");
        }
        }
        private void buscarGeneros(){
        try{
            
            ArrayList <Genero> generos = GeneroDAO.obterGenero();
            todosGenerosComboBox.setModel(new DefaultComboBoxModel<>(generos.toArray(new Genero[0])));
        }
        catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Tente novamente mais tarde");
        }
        
        
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        todosGenerosComboBox = new javax.swing.JComboBox();
        meusGenerosComboBox = new javax.swing.JComboBox();
        adicionarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Meus generos preferidos"));

        todosGenerosComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        todosGenerosComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Todos os generos"));
        todosGenerosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosGenerosComboBoxActionPerformed(evt);
            }
        });

        meusGenerosComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        meusGenerosComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Meus generos"));
        meusGenerosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meusGenerosComboBoxActionPerformed(evt);
            }
        });

        adicionarButton.setText("Adicionar");
        adicionarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adicionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarButtonActionPerformed(evt);
            }
        });

        removerButton.setText("Remover");
        removerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Voltar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(adicionarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(todosGenerosComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(meusGenerosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(todosGenerosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meusGenerosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarButtonActionPerformed
        // TODO add your handling code here:
        int id = 0;
        int generoId = 0;
        int userId = 0;
        Genero genero = (Genero)todosGenerosComboBox.getSelectedItem();        
        generoId = (genero.getId());
        String generoDescricao = "";
        try{
        userId = User_MusicaDAO.pegarUserId(usuario);        
        }catch(Exception e){
            e.printStackTrace();
        }
        
        User_Genero uG = new User_Genero(id,userId,generoId,generoDescricao);
        try{
            if(User_GeneroDAO.jaAdicionado(uG)){
                JOptionPane.showMessageDialog(null,"Você já possui esse genero como preferido.");
                return;
            }if(generoId == 0){
                JOptionPane.showMessageDialog(null,"Selecione seu genero antes.");
            }else{
                User_GeneroDAO.inserir(uG);
                JOptionPane.showMessageDialog(null,"Genero cadastrado!");
                buscarMeusGeneros();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Por favor tente mais tarde.");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_adicionarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ClienteTela clienteTela = new ClienteTela(usuario);
        try{
            clienteTela.setVisible(true);
            this.setVisible(false);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Por favor tente mais tarde.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void todosGenerosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosGenerosComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_todosGenerosComboBoxActionPerformed

    private void meusGenerosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meusGenerosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meusGenerosComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneroTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox meusGenerosComboBox;
    private javax.swing.JButton removerButton;
    private javax.swing.JComboBox todosGenerosComboBox;
    // End of variables declaration//GEN-END:variables
}
