/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Musica;
import java.util.ArrayList;
import DAO.MusicaDAO;
import DAO.User_MusicaDAO;
import Model.User;
import Model.User_Musica;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class MusicaTela extends javax.swing.JFrame {

    /**
     * Creates new form MusicaTela
     */
    String usuario;
    public MusicaTela(){
        
    }
    
    public MusicaTela(String usuario) {
        super("Avaliar musica");
        this.usuario = usuario;
        initComponents();
        buscarMusicas2();
        setLocationRelativeTo(null);
        usuarioTextField.setText(usuario);
        usuarioTextField.setEditable(false);
    }
    int usuarioId = 0;
    private void buscarMusicas2(){
        try{
        usuarioId =User_MusicaDAO.pegarUserId(usuario);                 
        
    }catch(Exception e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(null,"Não foi possivel,tente mais tarde");
     }try{
         ArrayList<Musica> musicas = User_MusicaDAO.obterMusica(usuarioId);
         musicasComboBox.setModel(new DefaultComboBoxModel<>(musicas.toArray(new Musica[0])));
         
     }catch(Exception e){
         e.printStackTrace();
     }
    }

    
    private void buscarMusicas(){
        try{
            
            ArrayList <Musica> musicas = MusicaDAO.obterMusica();
            musicasComboBox.setModel(new DefaultComboBoxModel<>(musicas.toArray(new Musica[0])));
           
            
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Tente novamente mais tarde");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        musicasComboBox = new javax.swing.JComboBox();
        notaDoisRadioButton = new javax.swing.JRadioButton();
        notaUmRadioButton = new javax.swing.JRadioButton();
        notaTresRadioButton = new javax.swing.JRadioButton();
        notaQuatroRadioButton = new javax.swing.JRadioButton();
        notaCincoRadioButton = new javax.swing.JRadioButton();
        avaliarButton = new javax.swing.JButton();
        usuarioTextField = new javax.swing.JTextField();
        voltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Avaliaçoes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Avaliar musica"));

        musicasComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        musicasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicasComboBoxActionPerformed(evt);
            }
        });

        buttonGroup1.add(notaDoisRadioButton);
        notaDoisRadioButton.setText("2");

        buttonGroup1.add(notaUmRadioButton);
        notaUmRadioButton.setText("1");
        notaUmRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaUmRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(notaTresRadioButton);
        notaTresRadioButton.setText("3");

        buttonGroup1.add(notaQuatroRadioButton);
        notaQuatroRadioButton.setText("4");

        buttonGroup1.add(notaCincoRadioButton);
        notaCincoRadioButton.setText("5");
        notaCincoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaCincoRadioButtonActionPerformed(evt);
            }
        });

        avaliarButton.setText("Avaliar");
        avaliarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        avaliarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliarButtonActionPerformed(evt);
            }
        });

        usuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        usuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextFieldActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar");
        voltarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(musicasComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(notaUmRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notaDoisRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notaTresRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notaQuatroRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notaCincoRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(avaliarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(musicasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(notaUmRadioButton)
                            .addComponent(notaDoisRadioButton)
                            .addComponent(notaTresRadioButton)
                            .addComponent(notaQuatroRadioButton)
                            .addComponent(notaCincoRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avaliarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musicasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicasComboBoxActionPerformed
        // TODO add your handling code here:
        Musica musica = (Musica)musicasComboBox.getSelectedItem();
        int musicaId = musica.getCodigo();
        
        
    }//GEN-LAST:event_musicasComboBoxActionPerformed

    private void notaUmRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaUmRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaUmRadioButtonActionPerformed

    private void avaliarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliarButtonActionPerformed
        // TODO add your handling code here:
        
    String login = usuarioTextField.getText();
    int musicaId;
    int nota =0;
    int userId =0;
    double media = 0;
    int id = 0;
       //buttons
       notaUmRadioButton.setActionCommand("1");
       notaDoisRadioButton.setActionCommand("2");
       notaTresRadioButton.setActionCommand("3");
       notaQuatroRadioButton.setActionCommand("4");
       notaCincoRadioButton.setActionCommand("5");
       //
  
     try{
     nota = Integer.parseInt(buttonGroup1.getSelection().getActionCommand());
     }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Selecione a nota antes.");
        e.printStackTrace();
    }

    Musica musica = (Musica)musicasComboBox.getSelectedItem();
    musicaId = musica.getCodigo();
    
    try{
        User_MusicaDAO.pegarUserId(login);
        userId = User_MusicaDAO.pegarUserId(login);                   
        
    }catch(Exception e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(null,"Não foi possivel,tente mais tarde");
     }
    User_Musica uM = new User_Musica(id, musicaId, nota, userId, media);
    

    try{
        if(nota > 0){
            if(User_MusicaDAO.jaAvaliou(uM)){
                JOptionPane.showMessageDialog(null,"Você já avaliou essa musica.");
            }else if(buttonGroup1.getSelection() != null){
                User_MusicaDAO.inserir(uM);{
                JOptionPane.showMessageDialog(null,"Musica avaliada com sucesso!");
            }
            }
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Por favor tente mais tarde");
        e.printStackTrace();
    }
    
    }//GEN-LAST:event_avaliarButtonActionPerformed

    private void usuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextFieldActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_usuarioTextFieldActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        ClienteTela ct = new ClienteTela(usuario);
        ct.setVisible(false);
        this.setVisible(false);
        ct.setVisible(true);
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void notaCincoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaCincoRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaCincoRadioButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicaTela().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avaliarButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox musicasComboBox;
    private javax.swing.JRadioButton notaCincoRadioButton;
    private javax.swing.JRadioButton notaDoisRadioButton;
    private javax.swing.JRadioButton notaQuatroRadioButton;
    private javax.swing.JRadioButton notaTresRadioButton;
    private javax.swing.JRadioButton notaUmRadioButton;
    public static javax.swing.JTextField usuarioTextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
